version: '3.1'
services:
  # node-server:
  #   container_name: node
  #   build: .
  #   ports:
  #     - "3000:3000"

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: project
    ports:
      - "3306:3306"
